### ISSUE TITLE
ValueError: does not appear to be an ipv4 or ipv6 address

### ISSUE THREAD

**Issue by ApoG22** [samsammurphy/ee-atmcorr-timeseries#8]
Hello, I have trouble running your ee-timeseries method. I am pretty new to coding and overall not a very tech savy guy, but I managed to install docker and launch your dockerfile.

I run into a problem at the last step when you get to jupyter notebook with
`jupyter-notebook ee-atmcorr-timeseries.ipynb --ip='*' --port=8888 --allow-root`

What I get is this
```
Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/miniconda/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address
```
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/miniconda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/miniconda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/miniconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/miniconda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/miniconda/lib/python3.6/site-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/miniconda/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
```

Do you have any idea why is this happening? Is this an issue on my end or on yours? 

Your gee-atmcor-S2 for single images is working perfectly fine for me, but I don't think I am capable of modifying it on my own to run it for a ImageCollection object.

I appreciate any help, thanks :)

**Comment by jimoreira** [comment]
hi, i'm having that problem also. 
exactly the same, also no problem for the other repository.
i would love to use this tool! 
thanks

**Comment by jimoreira** [comment]
I found the solution, when opening the jupyter notebook, 
change the ip='*' por ip=0.0.0.0
i found that with either this one or the repo gee-atmcorr-s2, when the web is provided, instead of copy/pasting inside the web browser, open de Kitematic soft (i suppose that you should have it if you are running a docker container), in there there's going to be a list with containers, and the one active, y colour. In the right panel (web preview) you had an square with an arrow, hit there, and that would make the connection successfully with your browser, then you just need to copy/paste the token provided in the cmd, and the notebook works fine.
